### ISSUE TITLE
Move social links to bottom of sidebar for increased contrast

### ISSUE THREAD

**Issue by bithakr** [triplestrange/blackburn#1]
like some sort of space so that their it doesn't look like we have a ton of links

**Comment by PenguinSnail** [comment]
code updated, waiting for build to confirm fixed

**Comment by PenguinSnail** [comment]
Social Links as well as copyright are now at the bottom of the sidebar.
Updated a bit messily using absolute positioning of a class, but rendering appears good on mobile as well as desktop.
